'{''macadress'': u''0800274a508c'', ''name'': u''controller'', ''instance'': u''2'',
  ''hostname'': u''controller.amio.com'', ''ipadress'': u''192.168.0.2'', ''memory'':
  u''1024'', ''cpu'': u''2''}'
